import { Injectable, Logger } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { PrismaService } from '../prisma/prisma.service';

export interface AppNotification {
  id: string;
  userId: string;
  title: string;
  body: string;
  type: 'info' | 'warning' | 'success' | 'error';
  category: 'scan' | 'finding' | 'report' | 'system' | 'account';
  read: boolean;
  createdAt: string;
  metadata?: Record<string, any>;
}

const DATA_DIR = process.env.NODE_ENV === 'production'
  ? '/tmp/securelens-data'
  : join(process.cwd(), '.securelens-data');
const NOTIFICATIONS_FILE = join(DATA_DIR, 'notifications.json');

/**
 * Notifications are generated by system events (scan completed, critical finding
 * found, report generated). This service persists them to Postgres when available
 * and falls back to a JSON file otherwise, so notifications survive restarts.
 */
@Injectable()
export class NotificationsService {
  private readonly logger = new Logger(NotificationsService.name);

  constructor(private readonly prisma: PrismaService) {}

  async findAll(userId: string): Promise<AppNotification[]> {
    if (this.prisma.connected) {
      try {
        const rows = await this.prisma.notification.findMany({
          where: { userId },
          orderBy: { createdAt: 'desc' },
          take: 50,
        });
        return rows.map(this.serializeDb);
      } catch (err: any) {
        this.logger.warn(`DB notification fetch failed (${err.message}) → file fallback`);
      }
    }
    return this.fileStore().filter(n => n.userId === userId);
  }

  async create(data: {
    userId: string;
    title: string;
    body: string;
    type?: AppNotification['type'];
    category?: AppNotification['category'];
    metadata?: Record<string, any>;
  }): Promise<AppNotification> {
    const record: AppNotification = {
      id: randomUUID(),
      userId: data.userId,
      title: data.title,
      body: data.body,
      type: data.type ?? 'info',
      category: data.category ?? 'system',
      read: false,
      createdAt: new Date().toISOString(),
      metadata: data.metadata,
    };

    if (this.prisma.connected) {
      try {
        const created = await this.prisma.notification.create({
          data: {
            userId: record.userId,
            title: record.title,
            body: record.body,
            type: record.type,
            category: record.category,
            read: false,
            metadata: (record.metadata as any) ?? undefined,
          },
        });
        return this.serializeDb(created);
      } catch (err: any) {
        this.logger.warn(`DB notification create failed (${err.message}) → file fallback`);
      }
    }

    const store = this.fileStore();
    store.unshift(record);
    this.writeFile(store);
    return record;
  }

  async markRead(id: string, userId: string): Promise<void> {
    if (this.prisma.connected) {
      try {
        await this.prisma.notification.updateMany({ where: { id, userId }, data: { read: true } });
        return;
      } catch (err: any) {
        this.logger.warn(`DB markRead failed (${err.message}) → file fallback`);
      }
    }
    const store = this.fileStore();
    const item = store.find(n => n.id === id && n.userId === userId);
    if (item) { item.read = true; this.writeFile(store); }
  }

  async markAllRead(userId: string): Promise<void> {
    if (this.prisma.connected) {
      try {
        await this.prisma.notification.updateMany({ where: { userId, read: false }, data: { read: true } });
        return;
      } catch (err: any) {
        this.logger.warn(`DB markAllRead failed (${err.message}) → file fallback`);
      }
    }
    const store = this.fileStore();
    store.forEach(n => { if (n.userId === userId) n.read = true; });
    this.writeFile(store);
  }

  async remove(id: string, userId: string): Promise<void> {
    if (this.prisma.connected) {
      try {
        await this.prisma.notification.deleteMany({ where: { id, userId } });
        return;
      } catch (err: any) {
        this.logger.warn(`DB delete failed (${err.message}) → file fallback`);
      }
    }
    const store = this.fileStore();
    const idx = store.findIndex(n => n.id === id && n.userId === userId);
    if (idx !== -1) { store.splice(idx, 1); this.writeFile(store); }
  }

  async removeAll(userId: string): Promise<void> {
    if (this.prisma.connected) {
      try {
        await this.prisma.notification.deleteMany({ where: { userId } });
        return;
      } catch (err: any) {
        this.logger.warn(`DB deleteAll failed (${err.message}) → file fallback`);
      }
    }
    const store = this.fileStore();
    const filtered = store.filter(n => n.userId !== userId);
    this.writeFile(filtered);
  }

  // ─── file fallback ───────────────────────────────────────────────────────────
  private fileStore(): AppNotification[] {
    try {
      if (!existsSync(NOTIFICATIONS_FILE)) {
        mkdirSync(dirname(NOTIFICATIONS_FILE), { recursive: true });
        this.writeFile([]);
        return [];
      }
      const raw = readFileSync(NOTIFICATIONS_FILE, 'utf-8');
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed : [];
    } catch (err: any) {
      this.logger.error(`Notification file read failed: ${err.message}`);
      return [];
    }
  }
  private writeFile(store: AppNotification[]) {
    try {
      mkdirSync(dirname(NOTIFICATIONS_FILE), { recursive: true });
      writeFileSync(NOTIFICATIONS_FILE, JSON.stringify(store, null, 2));
    } catch (err: any) {
      this.logger.error(`Notification file write failed: ${err.message}`);
    }
  }
  private serializeDb(row: any): AppNotification {
    return {
      id: row.id,
      userId: row.userId,
      title: row.title,
      body: row.body,
      type: row.type ?? 'info',
      category: row.category ?? 'system',
      read: !!row.read,
      createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt),
      metadata: row.metadata ?? undefined,
    };
  }
}
